### ISSUE TITLE
Move repo to Dracula's official org

### ISSUE THREAD

**Issue by zenorocha** [dracula/kate#1]
Hello @nortexoid!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by nortexoid** [comment]
Hello Zeno!


Sounds good to me! I'm not sure how one transfers a repo but after a quick
search I see github help explains it.


I am currently in transit at the airport, but I'll start a transfer as soon
as I can.


Awesome color scheme, by the way!


Best,

Michael

**Comment by zenorocha** [comment]
Nice! Just sent you an invitation to join the org :)

**Comment by nortexoid** [comment]
Repo transfered :)

**Comment by zenorocha** [comment]
Nice! Can you rename it to `kate`, adapt the README to match the template (https://github.com/dracula/template) and add instructions on how to install? After that I can add it to the website ;D

**Comment by nortexoid** [comment]
Should be all good now!

**Comment by zenorocha** [comment]
Nice! I'll update the site ;)

**Comment by nortexoid** [comment]
Great!

**Comment by zenorocha** [comment]
https://draculatheme.com/kate/ ;)

**Comment by nortexoid** [comment]
Great, thanks!
